[package]
name = "nicho/rocketgame"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Viewport = "aspecky/viewportfitter@^1.0.0"
ZonePlus = "mattschrubb/zoneplus@^3.2.0"
Reflex = "littensy/reflex@^4.3.1"
Sift = "csqrl/sift@0.0.9"
Vide = "centau/vide@0.3.1"
Janitor = "howmanysmall/janitor@^1.15.7"
Signal = "call23re/goodsignal@^0.2.2"
Red = "red-blox/red@2.3.0"
Spr = "blackjackiee/spr@1.1.3"
Iris = "michael-48/iris@2.3.1"

[server-dependencies]
ProfileService = "alreadypro/profileservice@^1.0.4"

[place]
shared-packages = "game.ReplicatedStorage.Packages"